import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "../globals.css";

import Header from "@/components/header/Header";
import FooterSection from "@/components/footer-section/FooterSection";
import NoteState from "@/context/notes/NoteState";
import PreLoader from '@/components/loader/PreLoader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Fonts  */}
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link href="https://fonts.gstatic.com" rel="preconnect" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="index-page">
        <NoteState>
          <PreLoader />
          <Header />
            <main className="main">{children}</main>
          <FooterSection />
        </NoteState>
      </body>
    </html>
  );
}
